// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrozwljwWXLuEGFU5xGQ05gdEUlfaKeTo',
    appId: '1:576429329225:web:3b0ea8817bbaefab99a898',
    messagingSenderId: '576429329225',
    projectId: 'octarineflcrud',
    authDomain: 'octarineflcrud.firebaseapp.com',
    storageBucket: 'octarineflcrud.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqf9JDqaKnTHzleFEpbjbCoYKMmRpr9kc',
    appId: '1:576429329225:android:0a60253c4484d07a99a898',
    messagingSenderId: '576429329225',
    projectId: 'octarineflcrud',
    storageBucket: 'octarineflcrud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBB-mcsZXjpP32Myl-BhOUdI2wGFCFO-k',
    appId: '1:576429329225:ios:e53b456f7942753499a898',
    messagingSenderId: '576429329225',
    projectId: 'octarineflcrud',
    storageBucket: 'octarineflcrud.appspot.com',
    iosBundleId: 'com.example.horsePower',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBB-mcsZXjpP32Myl-BhOUdI2wGFCFO-k',
    appId: '1:576429329225:ios:fc3f5f0dbba619c299a898',
    messagingSenderId: '576429329225',
    projectId: 'octarineflcrud',
    storageBucket: 'octarineflcrud.appspot.com',
    iosBundleId: 'com.example.horsePower.RunnerTests',
  );
}
